### ISSUE TITLE
Shape difference between rod and cylinder

### ISSUE THREAD

**Issue by NagosCrit** [davidson16807/relativity.scad#12] opened 2016-10-09 08:23 UTC
```
    rod([6, 6, 2.25], anchor = [0,0,1], $class = "nut", $fn= 6);
    cylinder(d = 6, h = 2.25, $fn = 6);
```

if you try to compare this objects you will see that rod is wider and not really even hexagon;
        rod([6, 5.2, 2.25], anchor = [0,0,1], $class = "nut", $fn= 6);
        cylinder(d = 6, h = 2.25, $fn = 6);
experimantally I found than x/y ratio of 6 to 5.2 makes nearly even hexagon. This result seems to be odd, cause in first case we 6mm between two sides and two verticies. Checking a few nuts and specifications [http://archicad-talk.graphisoft.com/files/filepages_from_16._nuts__bolts__screws_and_washers_559.pdf] _see page 1 table 16.1 and page 2 figure 16.1(b)_, I would expected to see rod([6, 5.5, 2.25]) to be same size as d=6 cylinder, but it was still bigger.

I have to add and rod(... , $fn= 2^n) is fine, It means if u have vertex at +Pi/2 and -Pi/2. otherwise the rod is a bit wider at Y side.

**Comment by davidson16807** [comment] 2016-10-13 17:20
I've reproduced the behavior. Good observation. 

OK, I know what's going on. All primitives in relativity.scad go through a `resize()` operation. This allows object dimensions to be specified in arrays like `[6, 6, 2.25]` with minimal complexity. It looks something like this:

				resize(size) 
				cylinder(d=size.x, h=size.z, center=true);

It normally works, but when we set `$fn=6`, we're rending a sphere with six points, and we can be certain at least one of the axes on the xy plane will be smaller than the specified 6mm. The `resize()` will attempt to correct this, so you wind up with something that's definitely not a regular hexagon. 

I'll outline some paths forward:

 * prevent resize if `$fn` is below a threshold. If so what threshold and why? Is it a special case where `$fn==6`, since we can expect most people will only encounter this while rendering hexagons? Seems arbitrary.

* prevent resize if size.x == size.y. This is a more general, less arbitrary case. It doesn't completely address the behavior, but it should address the case most people should be concerned with. 

* Treat the behavior as correct, but introduce a new primitive for hexagons. This is the cleanest answer, but how often are people going to use it and will they know it exists when relativity doesn't have an equivalent primitive? Also, why not pentagons or septagons? Still arbitrary.

* Abandon resizing completely. Not going to happen, since this is what allows use of $parent_size for sizing objects. 

I'm more inclined to the second option, but is there any approach you'd like to see implemented? Which of these cases best suit your needs?

**Comment by NagosCrit** [comment] 2016-10-14 06:06
it would be great to have somekind of flag to change behavior of rod.
Because n-gons are very common and important in tech modeling, and you have to control treir shape. But currect behavior can be useful at greater $fn or in some cases.
The problem exists on every $fn != 2^n. I think flag is an optimal choise.

**Comment by davidson16807** [comment] 2016-10-18 21:56
I can agree with that. There will be a new parameter added to `rod()`. The parameter will be unique to the `rod()` primitive. The parameter name needs to either: 

1.) address the fact you may get unexpected behavior if declaring size using $parent_size
`box_sizing = T`
`exact_size = T`

or 2.) address the intent for use with regular polygons. 
`polygonal = F`
`ngon = F`
`regular = F`

`polygonal` is what I'm inclined to use if there's no other opinions otherwise.

**Comment by joukhaha** [comment] 2018-09-08 11:54
I also ran to this issue which seems to be still valid.

My quick fix for it was to rescale the rod by replacing the section
```
    _bounds = _rotate_matrix(_orient_angles(orientation)) * [size.x,size.y,size.z,1];
                
	_assign($parent_size = size, 
```
on line 961-963 of the rod module in relativity.scad with
```
    xscale = $fn%2 == 0 ? 1 : .5+.5*cos(180/$fn);
    yscale = max(sin(360/$fn*floor($fn/4)), sin(360/$fn*ceil(($fn)/4)));

    _bounds = _rotate_matrix(_orient_angles(orientation)) * [size.x*xscale,size.y*yscale,size.z,1];
                
    _assign($parent_size = [size.x*xscale, size.y*yscale, size.z], 
```


This assumes that the rod is supposed to have $fn fold symmetry in the rotation plane by default, and it simply readjusts the size in x and y directions if the polygon corners don't coincide with the x and y axis.

After quick testing this seems to reproduce the correct shapes and functionality. Do you think this will have a more serious adverse effect in some cases?

Thanks - relativity is a really great library, btw!

**Comment by davidson16807** [comment] 2022-11-05 22:02
@aleung's last PR attempts to address this issue. I'll close this issue since it's been up for a while but feel free to open a new issue if the new functionality isn't satisfactory

**Closed by davidson16807** 2022-11-05 22:02 UTC
